# This is a basic workflow to help you get started with Actions

name: test blang

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install deps
        run: |
          sudo apt install python3 python3-minimal python-is-python3 python3-pip python3-tk -y
        
      - name: Compile blang
        run: |
          chmod +x build1
          ./build1

      - name: Run test script
        run: |
          echo "say Never gonna give you up" > a.blang
          ./blang a.blang
          
